### ISSUE TITLE
how to build it in ros

### ISSUE THREAD

**Issue by rymakacem** [moveit/warehouse_ros_mongo#12]

**Comment by rymakacem** [comment]
i tried all sorts to build this project but i can't .
what are the following tasks that i can do to debug it .
thank you

**Comment by 5730289021-NN** [comment]
I've got to change the project name from 'warehouse_ros_mongo' >> 'warehouse_ros'
then go for catkin_make

**Comment by rhaschke** [comment]
`warehouse_ros` is a different package: https://github.com/ros-planning/warehouse_ros!
ROS Melodic provides both packages as binaries: http://repositories.ros.org/status_page/ros_melodic_default.html?q=warehouse
