### ISSUE TITLE
no kinetic-devel branch?

### ISSUE THREAD

**Issue by ugocupcic** [moveit/warehouse_ros_mongo#2]

**Comment by davetcoleman** [comment]
we don't make branches for a distro until we have a change that only applies to that distro. do you have something kinetic-specific that motivates the branching?

**Comment by ugocupcic** [comment]
Ah ok. No that's fine

Sent from a tiny keyboard, excuse the brevity.

> On 23 Sep 2016, at 18:47, Dave Coleman notifications@github.com wrote:
> 
> we don't make branches for a distro until we have a change that only applies to that distro. do you have something kinetic-specific that motivates the branching?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

## _We're hiring Software Developers! - visit our website for more details._

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)
