### ISSUE TITLE
 Could not find parameter for database plugin name

### ISSUE THREAD

**Issue by boonflies** [moveit/warehouse_ros_mongo#20]
I am trying to launch a moveit planning session and when I connect using the option available in Motion Planning tab of RVIZ, I get the following error,

[ WARN] [1542797213.812504241]: Interactive marker 'JJ:goal_shadow' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.
[ERROR] [1542797223.019927700]: Could not find parameter for database plugin name

**Comment by rhaschke** [comment]
You need to enable database support, e.g. for the demo.launch file like this:
`roslaunch panda_moveit_config demo.launch db:=true`
