### ISSUE TITLE
Dependency on mongodb-server-core

### ISSUE THREAD

**Issue by simonschmeisser** [moveit/warehouse_ros_mongo#31]
I tried following the benchmark tutorial but connecting to the database failed as it was not installed. Is there a reason why there is no dependency on `mongodb-server-core`?

**Comment by v4hn** [comment]
> Is there a reason why there is no dependency on `mongodb-server-core`?

Technically you could have the server running on a different machine, couldn't you?

If you are looking into the warehouse infrastructure, you might want to try
https://github.com/k-okada/warehouse_ros_sqlite unless you are bound to use mongodb.

**Comment by simonschmeisser** [comment]
I'm just trying to follow the tutorial for the benchmark to get some progress in my assistant PR ...

but if we have a sqlite backend we should promote that in the tutorials!

**Comment by v4hn** [comment]
> but if we have a sqlite backend we should promote that in the tutorials!

Well, nobody tested it really. :) Thus also nobody wrote tutorials.
@k-okada implemented the plugin a while ago.

**Comment by rhaschke** [comment]
I agree with @v4hn, that the database should be run separately. I think the documentation should be improved in the tutorials. Closing here.
