### ISSUE TITLE
Missing dependency mongodb-dev

### ISSUE THREAD

**Issue by davetcoleman** [moveit/warehouse_ros_mongo#5]
Travis is failing for this repo because of a missing rosdep rule for "mongodb-dev" in xenial. Does someone have any insights? @ugocupcic?

**Comment by ugocupcic** [comment]
I must admit I didn't check the rosdeps. But I think that mongodb-dev shouldn't be installed on Xenial (if it exists) as it's replaced by the mongocxx manual install step. The rosdep can probably be just dropped?

Sent from my iPad

> On 7 Oct 2016, at 07:18, Dave Coleman notifications@github.com wrote:
> 
> Travis is failing for this repo because of a missing rosdep rule for "mongodb-dev" in xenial. Does someone have any insights? @ugocupcic?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

## _We're hiring Software Developers! - visit our website for more details._

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by davetcoleman** [comment]
i can quickly merge in a PR for this :)

**Comment by ethanfowler** [comment]
I've just run into the same issue on kinetic - warehouse_ros_mongo's package.xml specifies a dependency on mongodb-dev, which doesn't exist past Trusty (see https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L3137). Shall I create a PR @davetcoleman?

**Comment by davetcoleman** [comment]
@ethanfowler yes please!

**Comment by ethanfowler** [comment]
Created PR #8.
